name: 'Send Google Hangouts Chat'
description: 'Send notification to Hangouts Chat via webhook.'
author: 'yuki0n0'

branding:
  icon: 'unlock'
  color: 'green'

inputs:
  key id:
    description: 'Key ID. Can get from App Store Connect.'
    required: true
  issuer id:
    description: 'UUID. Can get from App Store Connect.'
    required: true
  key:
    description: 'P8 private key. Can get from App Store Connect.'
    required: true

outputs:
  token:
    description: 'Generated token to use App Store Connect API.'

runs:
  using: 'node12'
  main: 'main.js'